const array1 = [
  {
    Sequence_No: 1,
    Operation: "Front Press",
    Machine_type: "Manual",
    Rate: 7,
    Attachment: "",
    Smv: 0.25,
    uid: "1",
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 2,
    Operation: "Back Press",
    Machine_type: "Manual",
    Rate: 5,
    Attachment: "",
    Smv: 0.2,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 3,
    Operation: "Back Patch Press",
    Machine_type: "Manual",
    Rate: 6,
    Attachment: "",
    Smv: 0.3,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 4,
    Operation: "Front Pocket Position Marking",
    Machine_type: "Manual",
    Rate: 10,
    Attachment: "",
    Smv: 0.3,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 5,
    Operation: "Hood Panel Join (2)",
    Machine_type: "4TH O/L",
    Rate: 15,
    Attachment: "",
    Smv: 0.55,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 6,
    Operation: "Lining Hood Panel Join (2)",
    Machine_type: "4TH O/L",
    Rate: 15,
    Attachment: "",
    Smv: 0.55,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 7,
    Operation: "Hood Join Front",
    Machine_type: "4TH O/L",
    Rate: 15,
    Attachment: "",
    Smv: 0.5,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 8,
    Operation: "Draw Cord Hole With Fusing",
    Machine_type: "B.H",
    Rate: 14,
    Attachment: "Gauge",
    Smv: 0.4,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 9,
    Operation: "Hood Top Stitch Front",
    Machine_type: "F/L 3T",
    Rate: 16,
    Attachment: "",
    Smv: 0.4,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 10,
    Operation: "Hood Inner Tack",
    Machine_type: "S.N.L.S",
    Rate: 5,
    Attachment: "",
    Smv: 0.15,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 11,
    Operation: "Hood Closing",
    Machine_type: "4TH O/L",
    Rate: 8,
    Attachment: "",
    Smv: 0.3,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 12,
    Operation: "Front Pocket Hem",
    Machine_type: "F/L 3T",
    Rate: 12,
    Attachment: "Gauge",
    Smv: 0.25,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 13,
    Operation: "Front Pocket Attach With Trim",
    Machine_type: "S.N.L.S",
    Rate: 35,
    Attachment: "",
    Smv: 0.9,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 14,
    Operation: "Care Label Sew",
    Machine_type: "S.N.L.S",
    Rate: 8,
    Attachment: "",
    Smv: 0.25,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 15,
    Operation: "Shoulder Attach With Size Label",
    Machine_type: "4TH O/L",
    Rate: 12.5,
    Attachment: "",
    Smv: 0.35,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 16,
    Operation: "Hood Tack To Body",
    Machine_type: "S.N.L.S",
    Rate: 15,
    Attachment: "",
    Smv: 0.5,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 17,
    Operation: "Hood Attach",
    Machine_type: "4TH O/L",
    Rate: 15,
    Attachment: "",
    Smv: 0.35,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 18,
    Operation: "Back Neck Binding ",
    Machine_type: "F/L 2T",
    Rate: 13,
    Attachment: "Folder",
    Smv: 0.25,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 19,
    Operation: "Back Neck Binding End Tack ",
    Machine_type: "S.N.L.S",
    Rate: 9,
    Attachment: "",
    Smv: 0.35,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 20,
    Operation: "Back Neck Binding Closing ",
    Machine_type: "S.N.L.S",
    Rate: 14,
    Attachment: "",
    Smv: 0.45,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 21,
    Operation: "Front Neck Top Stitch ",
    Machine_type: "F/L 3T",
    Rate: 12,
    Attachment: "",
    Smv: 0.3,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 22,
    Operation: "Back Patch Attach",
    Machine_type: "S.N.L.S",
    Rate: 20,
    Attachment: "",
    Smv: 0.5,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 23,
    Operation: "HTL Attach To Back Patch",
    Machine_type: "Heat Seal",
    Rate: 9,
    Attachment: "",
    Smv: 0.25,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 24,
    Operation: "Sleeve Attach",
    Machine_type: "4TH O/L",
    Rate: 16,
    Attachment: "",
    Smv: 0.6,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 25,
    Operation: "Arm Hole Top Stitch",
    Machine_type: "F/L 3T",
    Rate: 15,
    Attachment: "",
    Smv: 0.5,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 26,
    Operation: "Side Seam With Label",
    Machine_type: "4TH O/L",
    Rate: 20,
    Attachment: "",
    Smv: 0.7,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 27,
    Operation: "Cuff Rib Ring Make+Attach With Turn",
    Machine_type: "4TH O/L",
    Rate: 23,
    Attachment: "",
    Smv: 0.55,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 28,
    Operation: "Bottom Rib Ring Make+Attach",
    Machine_type: "4TH O/L",
    Rate: 21,
    Attachment: "",
    Smv: 0.6,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 29,
    Operation: "Cuff Top Stitch ",
    Machine_type: "F/L 3T",
    Rate: 16,
    Attachment: "",
    Smv: 0.4,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 30,
    Operation: "Bottom Rib Top Stitch",
    Machine_type: "F/L 3T",
    Rate: 15,
    Attachment: "",
    Smv: 0.3,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 31,
    Operation: "Arm Hole Top Stitch",
    Machine_type: "Manual",
    Rate: 11,
    Attachment: "",
    Smv: 0.3,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 32,
    Operation: "Trimming",
    Machine_type: "",
    Rate: 18,
    Attachment: "",
    Smv: 0,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 33,
    Operation: "Press",
    Machine_type: "",
    Rate: 19,
    Attachment: "",
    Smv: 0,
    garmentStyle: "Pull Over Hood",
  },
  {
    Sequence_No: 34,
    Operation: "Rafu",
    Machine_type: " ",
    Rate: 3,
    Attachment: "",
    Smv: 0,
    garmentStyle: "Pull Over Hood",
  },
  //second array
  {
    Sequence_No: 1,
    Operation: "Tape Press",
    Machine_type: "Manual",
    Rate: 3,
    Attachment: "",
    Smv: 0.1,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 18,
    Operation: "Back Press",
    Machine_type: "Manual",
    Rate: 5,
    Attachment: "",
    Smv: 0.2,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 19,
    Operation: "Back Patch Press",
    Machine_type: "Manual",
    Rate: 6,
    Attachment: "",
    Smv: 0.3,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 20,
    Operation: "Front+Back Bottom Hem Stitch ",
    Machine_type: "F/L 5T",
    Rate: 16,
    Attachment: "",
    Smv: 0.4,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 2,
    Operation: "Shoulder Attach With Size Label",
    Machine_type: "4TH O/L",
    Rate: 13,
    Attachment: "",
    Smv: 0.35,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 3,
    Operation: "Shoulder Top Stitch",
    Machine_type: "F/L 2T",
    Rate: 10,
    Attachment: "",
    Smv: 0.25,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 4,
    Operation: "Neck Rib Ring Making+Attach",
    Machine_type: "4TH O/L",
    Rate: 18,
    Attachment: "",
    Smv: 0.5,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 5,
    Operation: "Back Neck Tape Attach",
    Machine_type: "S.N.L.S",
    Rate: 15,
    Attachment: "",
    Smv: 0.4,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 6,
    Operation: "Back Neck Tape Closing",
    Machine_type: "S.N.L.S",
    Rate: 19,
    Attachment: "",
    Smv: 0.4,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 7,
    Operation: "Front Neck Top Stitch",
    Machine_type: "F/L 2T",
    Rate: 12,
    Attachment: "",
    Smv: 0.2,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 8,
    Operation: "Sleeve Attach",
    Machine_type: "4TH O/L",
    Rate: 16,
    Attachment: "",
    Smv: 0.6,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 9,
    Operation: "Arm Hole Top Stitch",
    Machine_type: "F/L 3T",
    Rate: 15,
    Attachment: "Gauge",
    Smv: 0.5,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 10,
    Operation: "Side Seam With Label",
    Machine_type: "4TH O/L",
    Rate: 15,
    Attachment: "",
    Smv: 0.6,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 11,
    Operation: "Side Slit O/L",
    Machine_type: "4TH O/L",
    Rate: 8,
    Attachment: "",
    Smv: 0.3,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 12,
    Operation: "Side Slit Tack",
    Machine_type: "S.N.L.S",
    Rate: 10,
    Attachment: "",
    Smv: 0.4,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 13,
    Operation: "Side Slit Top Stitch",
    Machine_type: "S.N.L.S",
    Rate: 21,
    Attachment: "",
    Smv: 0.6,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 14,
    Operation: "Sleeve Hem",
    Machine_type: "F/L 5T",
    Rate: 12,
    Attachment: "Gauge",
    Smv: 0.4,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 15,
    Operation: "Care Label Sew",
    Machine_type: "S.N.L.S",
    Rate: 6,
    Attachment: "",
    Smv: 0.25,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 21,
    Operation: "Back Patch Attach",
    Machine_type: "S.N.L.S",
    Rate: 20,
    Attachment: "",
    Smv: 0.5,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 22,
    Operation: "HTL Attach To Back Patch",
    Machine_type: "Heat Seal",
    Rate: 10,
    Attachment: "",
    Smv: 0.25,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 23,
    Operation: "Trimming",
    Machine_type: "",
    Rate: 15,
    Attachment: "",
    Smv: 0,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 24,
    Operation: "Press",
    Machine_type: "",
    Rate: 16,
    Attachment: "",
    Smv: 0,
    garmentStyle: "Sweat Shirt",
  },
  {
    Sequence_No: 25,
    Operation: "Rafu",
    Machine_type: "",
    Rate: 3,
    Attachment: "",
    Smv: 0,
    garmentStyle: "Sweat Shirt",
  },
];
